version: '1.0.{build}'
image: Visual Studio 2017

#patch version in csproj file 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- cmd: >-
    dotnet restore geometry3Sharp_netstandard.csproj

    dotnet build geometry3Sharp_netstandard.csproj -c Release

    dotnet pack geometry3Sharp_netstandard.csproj -c Release
test: off
artifacts:
- path: bin\Release\*.nupkg
deploy:
  provider: NuGet
#  server:                  # remove to push to NuGet.org
  api_key:
    secure: DIcqDc7g8mWxhl3/G0MxoGVSnRJzdMvPZdJM7NbYjuy1tFhcF8hWA+nNoGntESX7
  on:
    appveyor_repo_tag: true	
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/